name: YTMinecraft
version: 1.0
main: ytminecraft.main.Main
commands:
  VIP추가:
    description: Adds a VIP player
  한글닉:
    description: Sets a player's nickname in Korean
  출석체크:
    description: Checks attendance
  상점:
    description: Opens the shop
  야생생성:
    description: Creates a new world
  워프:
    description: Teleports to a specified world
  평지생성:
    description: Creates a flat world
  리로드:
    description: Reloads the plugin
  월드리스트:
    description: Lists all current worlds